# Generated by Django 5.0.4 on 2024-04-12 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='slugify',
            new_name='slug',
        ),
    ]
